"""
allrun_writer.py — Generates OpenFOAM Allrun and Allclean scripts.

Why generate Allrun instead of writing it by hand?
---------------------------------------------------
Your current step 3 (changeDictionary loop) and step 4 (solver launch)
are typed manually every time.  The region list changes per assembly,
so the loop body changes too.

This module writes a complete, case-specific Allrun that covers:
  Step 1 : gmshToFoam              — convert .msh to OpenFOAM format
  Step 2 : transformPoints         — scale mm → m
  Step 3 : checkMesh               — catch bad elements before splitting
  Step 4 : splitMeshRegions        — split into per-region polyMesh
  Step 5 : apply_template.py       — deploy physics + material properties
  Step 6 : changeDictionary loop   — finalize boundary conditions per region
  Step 7 : chtMultiRegionSimpleFoam — run the solver

Allclean resets the case back to just the .msh file.

Both scripts are written to the case root directory so OpenFOAM's
runApplication / runParallel logging conventions work correctly.
"""

import os
import stat


# =============================================================================
# WRITER
# =============================================================================

class AllrunWriter:
    """
    Writes Allrun and Allclean into the case root directory.
    """

    def write(
        self,
        case_dir: str,
        msh_file: str,           # relative path to .msh from case root, e.g. "case.msh"
        template_dir: str,       # absolute path to template folder
        fluids: list[str],
        solids: list[str],
        scale: float = 0.001,    # transformPoints scale factor (0.001 = mm→m)
        parallel: bool = False,
        n_procs: int = 4,
        log = print,
    ) -> None:

        self._write_allrun(
            case_dir, msh_file, template_dir,
            fluids, solids, scale, parallel, n_procs
        )
        self._write_allclean(case_dir, msh_file)
        log(f"  Written: Allrun")
        log(f"  Written: Allclean")

    # ── Allrun ────────────────────────────────────────────────────────────

    def _write_allrun(
        self,
        case_dir: str,
        msh_file: str,
        template_dir: str,
        fluids: list[str],
        solids: list[str],
        scale: float,
        parallel: bool,
        n_procs: int,
    ) -> None:

        all_regions = fluids + solids
        region_list = " ".join(all_regions)

        # changeDictionary block — one call per region
        change_dict_block = "\n".join(
            f'    runApplication -s "{r}" changeDictionary -region "{r}"'
            for r in all_regions
        )

        # Absolute path to main.py — immune to SCRIPT_DIR / relative path issues
        # note : __file__ is python built-in varaible for point current file which means allrun_writer.py 
        main_py = os.path.join(os.path.dirname(os.path.abspath(__file__)), "main.py")

        # Parallel decompose block
        decompose_block = ""
        parallel_run = ""
        reconstruct_block = ""
        if parallel:
            decompose_block = f"""
# --- Decompose all regions for parallel run ---
runApplication decomposePar -allRegions -force"""
            parallel_run = f"""
# --- Run solver in parallel ---
runParallel chtMultiRegionSimpleFoam"""
            reconstruct_block = f"""
# --- Reconstruct ---
runApplication reconstructPar -allRegions"""
        else:
            parallel_run = f"""
# --- Run solver ---
runApplication chtMultiRegionSimpleFoam"""

        script = f"""#!/bin/sh
# Allrun — generated by allrun_writer.py
# Regions: fluids={fluids}  solids={solids}
cd "${{0%/*}}" || exit 1
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# ==========================================================================
# STEP 1 — Convert .msh to OpenFOAM format
# ==========================================================================
runApplication gmshToFoam {msh_file}

# ==========================================================================
# STEP 2 — Scale from mm to m  (adjust -scale if your model uses different units)
# ==========================================================================
runApplication transformPoints -scale "({scale} {scale} {scale})"

# ==========================================================================
# STEP 3 — Check mesh quality before splitting
# ==========================================================================
runApplication checkMesh
if grep -q "FAILED" log.checkMesh; then
    echo "ERROR: checkMesh FAILED. Fix mesh quality before continuing."
    exit 1
fi

# ==========================================================================
# STEP 4 — Split into per-region polyMesh
# ==========================================================================
runApplication splitMeshRegions -cellZones -overwrite

# ==========================================================================
# STEP 5 — Deploy physics templates + material properties
# (apply_template.py is in the same directory as Allrun)
# ==========================================================================
TEMPLATE_DIR="{template_dir}"

python3 "{main_py}" deploy \\
    --template "$TEMPLATE_DIR" \\
    --case     "$(pwd)" \\
    --msh      "{msh_file}" \\
    --scale    "{scale}"

if [ $? -ne 0 ]; then
    echo "ERROR: apply_template failed."
    exit 1
fi

# ==========================================================================
# STEP 6 — changeDictionary for each region
# ==========================================================================
{change_dict_block}
{decompose_block}
{parallel_run}
{reconstruct_block}

echo ""
echo "✅  Simulation complete."
echo "    Post-process with: paraFoam -touchAll"
"""
        self._write_executable(os.path.join(case_dir, "Allrun"), script)

    # ── Allclean ──────────────────────────────────────────────────────────

    def _write_allclean(self, case_dir: str, msh_file: str) -> None:
        script = f"""#!/bin/sh
# Allclean — generated by allrun_writer.py
# Resets the case back to just the .msh file.
cd "${{0%/*}}" || exit 1
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

# Remove processor directories (parallel runs)
rm -rf processor*

# Remove splitMeshRegions output (constant/<region>/polyMesh)
# Keep only the top-level constant/ files (g, etc.)
find constant -mindepth 2 -name "polyMesh" -type d -exec rm -rf {{}} + 2>/dev/null

# Remove deployed 0/ and system/ region subdirectories
find 0       -mindepth 1 -maxdepth 1 -type d -exec rm -rf {{}} +
find system  -mindepth 1 -maxdepth 1 -type d -exec rm -rf {{}} +
find constant -mindepth 1 -maxdepth 1 -type d -exec rm -rf {{}} +

# Remove OpenFOAM-converted mesh (but keep the original .msh)
rm -f constant/polyMesh/points constant/polyMesh/faces \\
      constant/polyMesh/owner  constant/polyMesh/neighbour \\
      constant/polyMesh/boundary

# Remove logs
rm -f log.*

echo "Case cleaned. Original .msh file kept: {msh_file}"
"""
        self._write_executable(os.path.join(case_dir, "Allclean"), script)

    # ── I/O ───────────────────────────────────────────────────────────────

    @staticmethod
    def _write_executable(path: str, content: str) -> None:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        # Make executable: chmod +x
        current = os.stat(path).st_mode
        os.chmod(path, current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
